# Generated by Django 5.1.5 on 2025-02-05 14:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumModerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Related User Model')),
            ],
        ),
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Post Content')),
                ('approved', models.BooleanField(default=False, verbose_name='Approval Status')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('downvote_users', models.ManyToManyField(related_name='downvoted_posts', to=settings.AUTH_USER_MODEL, verbose_name='Users Who Downvoted')),
                ('upvote_users', models.ManyToManyField(related_name='upvoted_posts', to=settings.AUTH_USER_MODEL, verbose_name='Users Who Upvoted')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_posts', to=settings.AUTH_USER_MODEL, verbose_name='Related User')),
            ],
        ),
        migrations.CreateModel(
            name='ForumPostReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.forumpost', verbose_name='Related Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Related User Model')),
            ],
        ),
    ]
