# Generated by Django 5.1.5 on 2025-02-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='title',
            field=models.CharField(default='', max_length=500, verbose_name='Post Title'),
        ),
    ]
